@extends('layouts.admin')
@section('title','Meal Plan Templates · FitWithSaju Admin')
@section('heading','Meal plan templates')
@section('subheading','Publish reusable weekly nutrition-plan structures using stable recipe IDs.')
@section('page_actions')<a class="btn btn-primary" href="{{ route('admin.meal-templates.create') }}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 5v14M5 12h14"/></svg>New template</a>@endsection
@section('content')
<div class="toolbar-card"><div class="toolbar"><form class="filter-form" method="GET"><div class="filter-grow"><input class="input" name="search" value="{{ request('search') }}" placeholder="Search template"></div><select class="select" style="max-width:170px" name="status"><option value="">All statuses</option>@foreach(['draft','published','inactive'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="btn btn-light">Filter</button>@if(request()->hasAny(['search','status']))<a class="btn btn-light" href="{{ route('admin.meal-templates.index') }}">Reset</a>@endif</form></div></div>
<div class="card table-card"><div class="table-wrap"><table class="table"><thead><tr><th>Template</th><th>Goal</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>@forelse($templates as $template)<tr><td><div class="entity-title">{{ $template->name }}</div><div class="entity-meta">{{ $template->slug }}</div></td><td><span class="chip">{{ $template->goal }}</span></td><td><span class="badge {{ $template->status==='published' ? 'on':($template->status==='draft'?'neutral':'off') }}">{{ ucfirst($template->status) }}</span></td><td class="muted" style="font-size:11px">{{ $template->updated_at?->format('M j, Y g:i A') }}</td><td><a class="btn btn-light btn-sm" href="{{ route('admin.meal-templates.edit',$template) }}">Edit</a></td></tr>@empty<tr><td colspan="5" class="table-empty">No meal plan templates found.</td></tr>@endforelse</tbody></table></div></div>
@include('components.admin-pagination',['paginator'=>$templates])
@endsection
